apiVersion: v1
kind: Service
metadata:
  name: anchor
  namespace: gridtokenx
  labels:
    app: anchor
    component: blockchain
spec:
  type: ClusterIP
  ports:
  - port: 8899
    targetPort: 8899
    protocol: TCP
    name: rpc
  - port: 8900
    targetPort: 8900
    protocol: TCP
    name: websocket
  selector:
    app: anchor
