apiVersion: v1
kind: Service
metadata:
  name: smartmeter
  namespace: gridtokenx
  labels:
    app: smartmeter
    component: simulator
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: smartmeter
