apiVersion: v1
kind: Service
metadata:
  name: solana-validator
  namespace: gridtokenx
  labels:
    app: solana-validator
    component: blockchain
spec:
  type: ClusterIP
  ports:
  - port: 8899
    targetPort: 8899
    protocol: TCP
    name: rpc
  - port: 8900
    targetPort: 8900
    protocol: TCP
    name: websocket
  - port: 9900
    targetPort: 9900
    protocol: TCP
    name: faucet
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: gossip
  selector:
    app: solana-validator
