apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: gridtokenx
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
  namespace: gridtokenx
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading
  namespace: gridtokenx
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: gridtokenx
spec:
  replicas: 1
