apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gridtokenx

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
  - configmap-patch.yaml
  - deployment-patches.yaml

images:
  - name: gridtokenx/apigateway
    newTag: dev
  - name: gridtokenx/explorer
    newTag: dev
  - name: gridtokenx/trading
    newTag: dev
  - name: gridtokenx/website
    newTag: dev
  - name: gridtokenx/smartmeter
    newTag: dev
  - name: gridtokenx/anchor
    newTag: dev
  - name: gridtokenx/solana-test-validator
    newTag: latest
